namespace StudentProjects.Application.Contracts;
public record LoginRequest(string Email, string Password);
public record LoginResponse(string AccessToken, string RefreshToken, Guid UserId, string Role);
public record TopicCreateRequest(string Title, string Description, string? Objective, string? ProposedTechnology);
public record LecturerRequestCreate(Guid TopicId, Guid LecturerUserId, Guid RegistrationPeriodId);
public record CapacityUpdateRequest(int MaximumStudents);
public record ProgressUpdateRequest(Guid MilestoneId, int PercentComplete, string WorkDone, string? Note);
public record MilestoneCreateRequest(Guid ProjectId, string Title, DateTimeOffset StartAt, DateTimeOffset DeadlineAt, string? ExpectedResult);
public record MilestoneSubmissionRequest(Guid MilestoneId, string ResultSummary, string? DocumentReference);
public record ReviewRequest(string? Feedback);
public record RepositoryLinkRequest(Guid ProjectId, string RepositoryUrl);
